--- #YAML:1.0
name: Posy-Plugin-FileStats
version: 0.40
author:
  - Kathryn Andersen
abstract: Posy plugin to cache file statistics
license: perl
requires:
  File::MMagic: 1.22
  File::stat: 1
  Posy: 0.4
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::FileStats:
    file: lib/Posy/Plugin/FileStats.pm
    version: 0.40
generated_by: Module::Build version 0.2607
